### ISSUE TITLE
Possible improvements for template and converter

### ISSUE THREAD

**Issue by dalito** [nfdi4cat/voc4cat-tool#124]
*Taken over from https://github.com/nfdi4cat/VocExcel/issues/2*

Ideas are marked as done here if they have been implemented in dev-1.0.0 branch (and therefore become part of v1.0.0).

### Template

This is for discussing possible future structural changes. This is not urgent but may serve as a checklist to review before the next big template-version step (in descending priority):

- [x] ~~Get rid of "Additional Concept Features" sheet because it is hard to work with only numeric IDs without knowing the preferred labels. The columns could be moved to the Concepts sheet.~~ Solved in another way in #253 already released as part of [v0.9.0](https://github.com/nfdi4cat/voc4cat-tool/releases/tag/v0.9.0).
- [x] The size of a collection is currently constrained by the maximum number of characters in xlsx cells (32767 chars). Depending on the IRI-length this may correspond to a few thousand concepts per collection (which is probably large enough for most applications). However, the UX how the membership in a collection is added or edited is rather poor. It would be much nicer, if membership could be marked in the concept sheet. This could be done by adding a memberOf column in sheets "Concept" with all collection-URIs the concept is member of. Then Excel filters could also be used efficiently to edit/review membership of Concepts in Collections. If we change the template like this, the limit on the number of collections goes away.
  - v1.0: Added `member_of_collections` and `member_of_ordered_collection` columns to Concepts sheet.
- [x] support for skos:altLabel in multiple languages. Currently it is assumed that all (comma-separated) altLabels are always given in the default language "en".
  - v1.0: altLabel supports multiple languages.
- [x] Support different languages for collection prefLabel.
  - v1.0: prefLabel supports multiple languages.
- [x] Make multi-language data entry easier by specifying just one language per line in the concept sheet.
- [x] Put version of template to a better place (ConceptScheme sheet). - Released as part of [v0.10.0](https://github.com/nfdi4cat/voc4cat-tool/releases/tag/v0.10.0)
- [x] Use a different separator than comma in xlsx cells. Users often use a comma as part of the text and/or use a semicolon as separator because they are used to semicolons from Excel formulas. It is suggested to separate urls from other urls or text by space (and/or) newline. For pure text fields (alternate label), we should consider to use a vertical bar | as separator.
  - v1.0: The separator can be configured in the xlsx/pydantic model.
- [x] Add a notes/feedback column (skos:editorialNote) for editorial purposes. It could be used by tools (or humans) to add notes which are relevant for  editing the concept/collection. This column may also be used by checking tools.
  - v1.0: Added `editorial_note` column to Concepts, Collections, and Concept Scheme sheets.
- [x] Change provenance column to skos:changeNote column to store change notes including date and author. Allow multiple line each with `<date> <gh-name> <change-note-text>`. This structure will be validated so that correct DC:provenance data can be created for each concept & collection. (related: #122)
  - v1.0: Added `change_note` column (skos:changeNote) to Concepts, Collections, and Concept Scheme sheets. Also added `provenance` column with git blame URL links via configurable `provenance_url_template`.
- [x] Support two ways of giving credit to used sources:
  - (i) vebratim copies; the source should be entered in columns "Source Vocab" (dct:source), "Source Vocab license", "Source Vocab Rights holder"
  - (ii) definitions influenced by other sources; these should be entered in "Influenced by IRIs" column.
  - v1.0: Added columns `source_vocab_iri`, `source_vocab_license`, `source_vocab_rights_holder`, and `influenced_by_iris` to Concepts sheet.
- [x] ~~Add a status column with states proposed/accepted/obsolete~~ Auto generate skos:historyNote with date & state upon change. Suggested states to track: created, obsoleted because ... (see next point). This information will not be present in Excel but only in turtle.
  - v1.0: Since skos:historNote is just text it is not well suitable for structured information. In v1.0 we add a link to git-blame output in GitHub to access concept history.
- [x] Add column for reason of obsoletion and provide pre-defined reasons for obsoletion (inspired by https://wiki.geneontology.org/index.php/Obsoleting_an_Existing_Ontology_Term)
  - The term is not clearly defined and usage has been inconsistent.
  - This term was added in error.
  - More specific terms were created.
  - This term was converted to a collection.
  - The meaning of the term is ambiguous.
  - There is no evidence that this function/process/component exists.
  - v1.0: Added `obsolete_reason` column to Concepts and Collections sheets. Also supports `replaced_by` notation in change_note for deprecated concepts/collections.
- [x] (maybe) Use [tables](https://openpyxl.readthedocs.io/en/latest/worksheet_tables.html) instead of hard-coded cell-positions and sheet names. Tables can be found independently of their cell position and "home" sheet. This would give users more flexibility to adjust the layout. (previously suggested [here](https://github.com/surroundaustralia/VocExcel/issues/31#issue-1227553740))
  - v1.0 uses xlsx tables on all sheets.

Hierarchy representation:

- [x] switch from childrenIRI to parentIRI in concepts sheet - Released as part of [v0.10.0](https://github.com/nfdi4cat/voc4cat-tool/releases/tag/v0.10.0)

Collection membership:

- [x] Use a new column skos:member (meaning "is member of") in concepts sheet to express membership of a concept in 0...N ollections.
  - v1.0: Added `member_of_collections` column to Concepts sheet.
- [x] Change the column in collection sheet to express "is member of" for collections in collections.
  - v1.0: Added `parent_collection_iris` column to Collections sheet for nested collections.

### Converter

- [x] All users/editors of a vocabulary should use the same prefixes. That each user can adjust prefixes individually via the Prefixes sheet does not make sense. Instead the prefix sheet should be read-only. The shared prefixes for a vocabulary can already be defined in `idranges.toml`. Prefix-sheet was made read-only in #263, released in [v0.9.0](https://github.com/nfdi4cat/voc4cat-tool/releases/tag/v0.9.0).
- [x] The user should never change anything in the concept scheme sheet of the template. So the sheet should just be created as info-page but never read. To realize this we need to extend the vocabulary configuration file. Some additional fields should be added (e.g. homepage-URL or issue-tracker-URL).
  - v1.0: ConceptScheme metadata is now read from `idranges.toml` config. Added fields: `title`, `description`, `created_date`, `creator`, `publisher`, `custodian`, `catalogue_pid`, `documentation`, `issue_tracker`, `helpdesk`, `repository`, `homepage`, `conforms_to`. The ConceptScheme sheet is generated from config and enriched with contributor information derived from ID range usage.
- (maybe) Output [SKOS-XL](https://www.w3.org/TR/skos-reference/#xl). Then a unique ID for each translation allows to make statements on the translated concept, e.g. about provenance of the translation.
  - Not considered worth adding for v1.0: Translations / multilanguage are not key in voc4cat-tool maintained vocabularies today.
- [x] (maybe) Support [skos:orderedCollection](https://www.w3.org/TR/skos-reference/#collections)
  - v1.0: Added `ordered` column to Collections sheet and `member_of_ordered_collection` column to Concepts sheet with position notation.
- (maybe) Support not-yet supported SKOS relations like [skos:broaderTransitive](https://www.w3.org/TR/skos-reference/#broaderTransitive), [skos:narrowerTransitive](https://www.w3.org/TR/skos-reference/#narrowerTransitive)
  - Not considered worth adding for v1.0. If required, write RDF-enrichment script to add tranisitive relations.

### Profile

- [x] Allow prefLabel in multiple languages (see [vocexcel#1](https://github.com/RDFLib/VocExcel/issues/1)). We probably need our own SHACL vocabulary profile.
  - v1.0: altLabel supports multiple languages.
- Several changes suggested above e.g. the use of skos:notes require profile changes.
  - Profile changes are not essential for v1.0 and maybe be done later.
- [x] Support configurable SHACL profile for validation.
  - v1.0: Added `profile_local_path` config option to specify a custom SHACL profile file relative to `idranges.toml` location.

**Comment by dalito** [comment]
Here is a draft for a new xlsx template structure that includes all of the changes proposed above except for the last one (use of tables). Note that the help sheet has not yet been adapted.
[photocatalysis_example_Template-0.5-r2023-08-04.xlsx](https://github.com/nfdi4cat/voc4cat-tool/files/12257948/photocatalysis_example_Template-0.5-r2023-08-04.xlsx)

**Comment by dalito** [comment]
The proposed new template (2nd draft) cannot handle that skos:collections may have not only concepts but also other collectionns as [skos:member](https://www.w3.org/2009/08/skos-reference/skos.html#member).

**Comment by markdoerr** [comment]
I like esp. the first three items on the list, @dalito :)

**Comment by markdoerr** [comment]
Hi @dalito,

regarding the collection item in the checklist above: 
I would suggest the following process:
1. collections (IRI and name) are registered in the "collections" tab
2. in the "concept" tab each collection gets its own column (column name must match the collection name)
3. to add a concept to a collection, simply a cross ("X") needs to be set in the corresponding column

**Comment by dalito** [comment]
Like the green column Q of the [example file](https://github.com/nfdi4cat/voc4cat-tool/issues/124#issuecomment-1665103209)? There would be one column per collection in concept sheet. I just added one to show the idea.

**Comment by dalito** [comment]
Collection in collection would be modelled in collections sheet. This is not yet in the template draft IIRC.

**Comment by markdoerr** [comment]
> Like the green column Q of the [example file](https://github.com/nfdi4cat/voc4cat-tool/issues/124#issuecomment-1665103209) (2nd draft)? There would be one column per collection in concept sheet. I only added a single column to show the idea.

yes, @dalito, and then in the cells the user just adds an "X" (small or capital should be allowed) - boolean would be nicer, but most non-programmers are not so familiar with this concept of True and False ;)

**Comment by markdoerr** [comment]
Hi @dalito, 
here some further usability improvement suggestions:
Children IRIs should be referenced by preferred Label (this is more readable and less error prone).

If possible, I would omit the Concept IRI from the Concept tab, completely. The Concept IRIs with the right padding could be automatically generated by the CI-pipeline. As numbering for the IRIs one could then just use the line numbers of the excel sheet. That would simplify the sheet.

**Comment by dalito** [comment]
> Children IRIs should be referenced by preferred Label"

This easily breaks if a label is changed at one place but another is forgotten. In the past there were many problems with misspellings, case, white space or separator use. IDs are the solution to this.

It is possible to use in indentation for hierarchy as alternative when using voc4cat-tool locally (pip / pipx installed).

**Comment by dalito** [comment]
@markdoerr In the childrenIRI field we could perhaps append the preferred label after each IRI. The label would just be present for convenience but would be stripped off when reading.
```
https://example.org/0000105 (infrared)
https://example.org/0000106 (visible)
https://example.org/0000107 (ultraviolet)
```

**Comment by dalito** [comment]
I have updated the first message and put a new (3rd) draft for the template "1.0" to the 2nd message which addresses all issue/ideas that came up until now.

**Comment by markdoerr** [comment]
Thanks @dalito,
sounds good, I will have a look ...

**Comment by dalito** [comment]
Julia @schumannj proposed in https://github.com/nfdi4cat/voc4cat/issues/113 to replace ChildrenIRI by ParentIRI. For vocabularies where most concepts have parents (like in voc4cat) this makes a lot of sense. But flat concept schemes, in which most concepts are top-level concepts and only few narrower concepts exists, are better expressed with ChildrenIRIs as it is now. 

So should it be configurable at vocabulary level to use either or? Is the added complexity justified?

**Comment by markdoerr** [comment]
I personally prefer the parent relation in building hierarchies, because each child can have at most one parent (which is simpler than parents having multiple children - like in real life ;). ) For flat hierarchies, the difference is of course not big as @dalito pointed out. But, will we stay "flat" in the future ? Since one never knows, I would opt for the simpler (=ParentIRI) solution, suggested by @schumannj, since in the worst case one only would need to add one parent to a child (poor child).

**Comment by dalito** [comment]
Following the thinking that entering broader (parent) is easier than narrower (children), we should also add a column "member of" to the concept sheet in order to enter membership in collections directly at the concept instead of the current way of adding all collection members in the collection sheet.

With these two changes, I am no longer convinced that the original idea of merging the "Concepts", "Additional Concept Features", and "Collections" sheets into one sheet should be pursued. Instead I suggest to keep the 3-table-split, because:

- It matches with how people contribute. Typically you don't add concepts, new mappings and new collections all at once. But if the contributions are split (and they indeed have been split in voc4cat), then having one huge sheet will be less convenient to work with than 3 small sheets.
- Keeping 3 sheets would allow us to take a gentler approach to the goal of a significantly improved xlsx template. Both the code and the user experience could change incrementally avoiding problematic breaking changes.

**Comment by nmoust** [comment]
In a slightly relevant topic: A single excel cell fits 32767 characters. A URI in voc4cat is 41 characters long. If we add a comma and a blank space in between the URIs, a Collection or a Children cell can fit up to 762 members  (780 without the blank space).
